name: update precision

on:
  push:
    branches:
      - develop

jobs:
  determine-whether-update:
    name: Determine whether to update
    if: github.repository == 'PaddlePaddle/PaddleFleet'
    runs-on:
      group: APPROVAL
    outputs:
      need_change: ${{ steps.determine.outputs.need_change }}
    steps:
      - name: Cleanup
        run: |
          rm -rf * .[^.]*
      - name: Determine whether to update
        id: determine
        run: |
          set -x
          sleep 30
          response=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/PaddlePaddle/PaddleFleet/commits/${{ github.sha }}/pulls)
          pr_number=$(echo $response | jq -r '.[0].url' | awk -F'/' '{print $NF}')
          set +e
          wget --no-proxy --no-check-certificate https://paddle-github-action.cdn.bcebos.com/PaddleFleet/precision/PaddleFleet/${pr_number}/precision_list.txt
          if [ $? -eq 0 ]; then
            echo "need_change=true" >> "$GITHUB_OUTPUT"
          else
            echo "need_change=false" >> "$GITHUB_OUTPUT"
          fi

  update-precision-fleet:
    name: Update precision fleet
    needs: determine-whether-update
    if: needs.determine-whether-update.outputs.need_change == 'true'
    runs-on:
      group: APPROVAL
    steps:
      - name: Cleanup
        run: |
          rm -rf * .[^.]*
      - name: Setup python3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update precision
        env:
          AK: ${{ secrets.AK }}
          SK: ${{ secrets.SK }}
          GITHUB_TOKEN: ${{ github.token }}
          COMMIT_ID: ${{ github.sha }}
          GITHUB_REPO_NAME: ${{ github.repository }}
        run: |
          set -x
          python -m pip install bce-python-sdk==0.8.74
          export step="fleet"
          wget -q -O bos_new.tar.gz https://xly-devops.bj.bcebos.com/home/bos_new.tar.gz --no-check-certificate
          mkdir bos
          tar xf bos_new.tar.gz -C bos
          bash -x test/formers/integration_test/update_precision.sh

  # update-precision-formers:
  #   name: Update precision formers
  #   needs: determine-whether-update
  #   if: needs.determine-whether-update.outputs.need_change == 'true'
  #   uses: ./.github/workflows/precision_publish_wheel.yml
  #   secrets: inherit
